### ISSUE TITLE
Not compatible with gzdoomvr

### ISSUE THREAD

**Issue by bferguson3** [mmaulwurff/laser-sight#5]
Script error, "laser-sight-v0.6.pk3:zscript/ls_event_handler.zs" line 112:
ValueType not set
Script error, "laser-sight-v0.6.pk3:zscript/ls_event_handler.zs" line 123:
Unknown identifier 'Scale'
Script error, "laser-sight-v0.6.pk3:zscript/ls_event_handler.zs" line 124:
Unknown identifier 'Scale'

This isn't your fault so much as the openvr port of gzdoom, but I was wondering if there is a way around using these variables and perhaps using constants instead to get this working in VR. (Sorry I don't know much about Doom modding!)

**Comment by mmaulwurff** [comment]
Can you please provide a link to your gzdoomvr build, so I can check it on my side?

**Comment by mmaulwurff** [comment]
@bferguson3 , please tell me what gzdoomvr build and version do you use.

**Comment by knowsshit** [comment]
I just tried using it with GZDoomVR 4.8.2 from https://github.com/hh79/gzdoomvr and while laser-sight-v0.6.pk3 loaded without any errors, I cannot see any laser sights.

**Comment by mmaulwurff** [comment]
Cannot reproduce.  I don't have VR hardware. Run GZDoomVR 4.8.2 with wine on Linux. Had to enable Laser Sight in Laser Sight options (it's off by default).

![Screenshot_Doom_20220801_202832](https://user-images.githubusercontent.com/742823/182158906-c4ad3289-594f-4d3b-b3e2-24b946ccaea6.png)
